### ISSUE TITLE
User-contributed newsfeed

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/website#29]
I'd like to add a function to display user-contributed articles in a later stage.
They could be fetched via RSS and displayed in a list similar to the blog.

We can control the list of RSS feeds and specifically exclude or include entries using a jSON database.
Integration could be done using #28

**Comment by Croydon** [comment]
What do you mean with "articles"?
Blog posts? Forum posts?

**Comment by Fohlen** [comment]
Blog posts, forum posts, twitter posts, fork commit messages, whatever comes to your mind

**Comment by Fohlen** [comment]
This issue was moved to inexor-game/code#263
