### ISSUE TITLE
Ingame wiki / faq / knowledgebase

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/website#30]
We could render an in-game wiki on the website with markdown.
The files should go into ```blog-data``` and could also be available in the game using a NodeJS/markdown-renderer.
On our websites there should be a sort of knowledge-base, searchable with Ajax

**Comment by Croydon** [comment]
What should be the content of such a wiki?

**Comment by Fohlen** [comment]
Could be anything from general tips, tweaking settings, explanation on gamemodes or coop-edit guides..

**Comment by Croydon** [comment]
A wiki for these purposes are imo a post-stable job.

**Comment by Fohlen** [comment]
This issue was moved to inexor-game/code#262
